# x.0或者x.10以0结尾的需要加上引号如"x.0"
6.0:  # 文档中心大版本
    BCS: "6.0"   # 产品版本
    BestPractices: "7.0"
    BlueKingFamily: "7.0"
    CMDB: 3.9
    DeploymentGuides: "6.0"
    DevelopGuide: "7.0"
    Devops: "6.0"
    DocumentationContributorGuide: "7.0"
    FAQs: "6.0"
    FTA: 5.2
    GSE: 3.5
    IAM: 1.4
    ITSM: 2.5
    JOB: 3.2
    LogSearch: 4.2
    Monitor: 3.3
    NodeMan: "2.0"
    PaaS: 2.12
    QuickStart: "6.0"
    ReleaseNotes: "7.0"
    SOPS: 3.6
    UserManage: 2.2
    VersionLog: "6.0"
    VideoTutorial: "7.0"
    downloads: "7.0"
    BKnetwork: 6.1
    OnlineGuide: "7.0"
6.1:
    APIGateway: "1.10"
    BCS: 6.1
    BestPractices: "7.0"
    BlueKingFamily: "7.0"
    CMDB: "3.10"
    DeploymentGuides: 6.1
    DevelopGuide: "7.0"
    Devops:  "2.0"
    DocumentationContributorGuide: "7.0"
    FAQs: 6.1
    GSE: 3.6
    IAM: 1.8
    ITSM: 2.6
    JOB: 3.5
    LogSearch: 4.3
    Monitor: 3.6
    NodeMan: 2.2
    PaaS: 2.14
    QuickStart: "7.0"
    ReleaseNotes: "7.0"
    SOPS: 3.25
    UserManage: 2.4
    VersionLog: 6.1
    VideoTutorial: "7.0"
    downloads: "7.0"
    BKnetwork: 6.1
    OnlineGuide: "7.0"
6.2:
    APIGateway: "1.10"
    BestPractices: 7.1
    BlueKingFamily: "7.0"
    CMDB: "3.10"
    DeploymentGuides: 6.2
    DevelopGuide: "7.0"
    Devops: "2.0"
    DocumentationContributorGuide: "7.0"
    GSE: "2.0"
    IAM: 1.12
    ITSM: 2.6
    JOB: 3.7
    LogSearch: 4.6
    Monitor: 3.8
    NodeMan: 2.2
    PaaS: 2.14
    QuickStart: "7.0"
    ReleaseNotes: "7.0"
    SOPS: 3.28
    UserManage: 2.5
    VersionLog: 6.2
    VideoTutorial: "7.0"
    downloads: "7.0"
    BKnetwork: 6.1
    OnlineGuide: "7.0"
7.0:
    APIGateway: "1.10"
    BCS: 1.28
    BK-Base: "3.10"
    BestPractices: "7.0"
    BlueKingFamily: "7.0"
    CMDB: "3.10"
    DeploymentGuides: "7.0"
    DevelopGuide: "7.0"
    Devops: "2.0"
    DocumentationContributorGuide: "7.0"
    GSE: "2.0"
    IAM: 1.8
    ITSM: 2.6
    JOB: 3.6
    LessCode: "1.0"
    LogSearch: 4.3
    Monitor: 3.6
    NodeMan: 2.2
    PaaS: "1.0"
    QuickStart: "7.0"
    ReleaseNotes: "7.0"
    SOPS: 3.25
    UserManage: 2.4
    VersionLog: "7.0"
    VideoTutorial: "7.0"
    downloads: "7.0"
    OnlineGuide: "7.0"
7.1:
    APIGateway: "1.10"
    BCS: 1.28
    BK-Base: "3.10"
    BestPractices: 7.1
    BlueKingFamily: "7.0"
    CMDB: "3.10"
    DeploymentGuides: 7.1
    DevelopGuide: "7.0"
    Devops: "2.0"
    DocumentationContributorGuide: "7.0"
    GSE: "2.0"
    IAM: 1.12
    ITSM: 2.6
    JOB: 3.7
    LessCode: "1.0"
    LogSearch: 4.6
    Monitor: 3.8
    NodeMan: 2.2
    PaaS: "1.0"
    QuickStart: "7.0"
    ReleaseNotes: "7.0"
    SOPS: 3.28
    UserManage: 2.5
    VersionLog: 7.1
    VideoTutorial: "7.0"
    downloads: "7.0"
    OnlineGuide: "7.0"
